services:
  - docker

notifications:
  email:
    recipients:
      - leo@cuckoo.org
    on_success: never
    on_failure: always
  irc: "irc.perl.org#metacpan-travis"

before_script:
  - docker pull metacpan/metacpan-base || true

script:
  - cd base
  - docker build --pull --cache-from metacpan/metacpan-base --tag metacpan/metacpan-base .

before_deploy:
  - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASS"

deploy:
  provider: script
  script: docker push metacpan/metacpan-base
  on:
    branch: master

