services:
  - docker

env:
  global:
    - IMAGE_NAME: metacpan-base
    - DOCKER_HUB_NAME: "metacpan/${IMAGE_NAME}"
    - VERSION: "${TRAVIS_BUILD_NUMBER}"
    - VERSION_TAG: "${DOCKER_HUB_NAME}:${VERSION}"

notifications:
  email:
    recipients:
      - leo@cuckoo.org
    on_success: never
    on_failure: always
  irc: "irc.perl.org#metacpan-travis"

# Pull from docker hub so can use as cache for initial steps
before_script:
  - docker pull "$DOCKER_HUB_NAME" || true

# Perform build, make sure to pull image deps and build from the fetched version as cache
script:
  - cd base
  - docker build --pull --cache-from "$DOCKER_HUB_NAME" --tag $DOCKER_HUB_NAME --tag $VERSION_TAG .

before_deploy:
  - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWD"

# Deploy this build as a version AND as latest
deploy:
  - provider: script
    script: 
      - docker push "$DOCKER_HUB_NAME"
    on:
      branch: master
