version: '3'
services:
  web:
    image: metacpan-web:latest
    build:
      context: ./src/metacpan-web
    volumes:
      - web_carton:/carton
      - ./src/metacpan-web:/metacpan-web
    ports:
      - "5001:5001"
    networks:
      - web

networks:
  web:

volumes:
  web_carton:
