---
name: docker-compose container tests

on:
  push:
  schedule:
    # Every Sunday morning
    - cron: "15 4 * * *"
jobs:
  build:
    name: init and up
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - uses: actions/checkout@v1

      - name: init
        run: bin/metacpan-docker init

      - name: start environment
        run: docker-compose up -d --exit-code-from apitest apitest
      - name: run tests
        run: docker-compose exec -T apitest carton exec -- prove -lvr t/
      - name: down
        run: docker-compose down
